# 请求：从动作客户端发送到服务端，表明新目标

int32 order # 目标：斐波那契数列的order

---

# 结果： 当目标完成时，从服务器向客户端返回执行的结果

int32[] sequence # 结果：生成的对应order的斐波那契数列

---

# 反馈：从服务器向客户端定时发送的数据，内容是关于执行任务的过程信息

int32[] partial_sequence # 反馈： 当前已生成的数列部分


# 加完这些之后去看cmakelists
